version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - misspell
    - gosec
    - nilerr
    - unparam
    - prealloc
    - dupl
    - gocyclo
    - nakedret
  disable:
  settings:
    gocyclo:
        min-complexity: 15
    revive:
        severity: warning
    misspell:
        locale: US

formatters:
  enable:
    - gofumpt
